### ISSUE TITLE
some spelling issues

### ISSUE THREAD

**Issue by rvion** [agocorona/transient#17]
Amazing work ! 

few typos I found while reading:

-----------

> However, while spark is a framework, transient is a pure library where the primitives are first class in the language, and map-reduce is a particular operation __int__ transient, but it is not hard-coded in a rigid framework.

=> in

----------

```haskel
import Transient.EVars

main= keep $ do
  var <- newEVar
  comp1 <|>  comp3
  liftIO $ putStrLn "world"

comp1= do
   r <- readEVar var
   liftIO $ putStrLn r

comp2= writeEVar var "hello"
```
`comp1 <|> comp3`  => `comp1 <|> comp2`

-----------

> Like in the case of spark, reduce is the operation that executes __everithing__, while map is declarative. Let's see an example:

-> everything

**Comment by agocorona** [comment]
Thanks!. fixed.
