### ISSUE TITLE
Unbound variable n in tutorial

### ISSUE THREAD

**Issue by ysangkok** [agocorona/transient#20]
In the last example on input elements, this line occurs:

`r <- getRadio [fromStr v ++> setRadioActive v n | v <- ["red","green","blue"]]`

But n is not defined anywhere...

**Comment by geraldus** [comment]
Looks like a typo, `setRadioActive` have only one argument:

```hs
setRadioActive
  :: (Typeable a, Eq a, Show a)
  => a -> Widget (Radio a)
```

**Comment by ysangkok** [comment]
I think the extra argument is there cause [this definition from hplayground](https://github.com/agocorona/hplayground/blob/9328e3d96ed40bf35acf166de5ba967614dad4bb/src/Haste/HPlay/View.hs#L570) was used.

**Comment by agocorona** [comment]
Thanks for the correction!

Yes this is because, in the latest version of GHCJS.HPlay  I supressed the lambda expression coming from hplayground and MFlow, and I use a state variable to carry out the identifier of the radio buttons.
