### ISSUE TITLE
"mclustered" version on Hackage

### ISSUE THREAD

**Issue by AlexeyRaga** [agocorona/transient#7]
Could you please update Hackage to the version where `clustered`/`mclustered` issue is fixed?

**Comment by agocorona** [comment]
It was sent when i closed the issue.

Concerning the spurious messages in "slave" nodes, I think that i found it.
But It will take some time to upload the update

2015-10-25 12:10 GMT+01:00 Alexey Raga <notifications@github.com>:

> Could you please update Hackage to the version where clustered/mclustered
> issue is fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/transient/issues/7>.
>



-- 
Alberto.

**Comment by agocorona** [comment]
Ah, ok you mean Hackage, not git. I will do it right now.


2015-10-25 17:07 GMT+01:00 Alberto G. Corona <agocorona@gmail.com>:

> It was sent when i closed the issue.
>
> Concerning the spurious messages in "slave" nodes, I think that i found
> it. But It will take some time to upload the update
>
> 2015-10-25 12:10 GMT+01:00 Alexey Raga <notifications@github.com>:
>
>> Could you please update Hackage to the version where clustered/mclustered
>> issue is fixed?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/agocorona/transient/issues/7>.
>>
>
>
>
> --
> Alberto.
>



-- 
Alberto.

**Comment by agocorona** [comment]
SOLVED the spurious messages in remote nodes too. I uploaded it to git and hackage. 

Can you confirm it?

**Comment by AlexeyRaga** [comment]
It looks like it works better now.

I see that now only the node where I call "start" is printing the results (before all nodes were doing it). It seems logical to me too.

Thanks for the changes.

**Comment by agocorona** [comment]
Ok. 

The problem was due to switch variable that more or less indicates that the computation is acting as "slave" . 

      setSData WasRemote

That status variable was not shared by all the threads, so they executed the whole computation and not only the remote part. That in a single node was not observable neither in a two node cluster for some reason. 

Thanks for reporting this out.
