### ISSUE TITLE
`profits` example require a final `price` event

### ISSUE THREAD

**Issue by louispan** [agocorona/transient#8]
I'm not sure if this is the right place to submit this issue, but I notice that the `profits` example on [fpcomplete](https://www.fpcomplete.com/user/agocorona/a-monad-for-reactive-programming-part-1) require a final `price` event in the `eventList` in order to print out the `total`.

For example, if I changed the `eventList` to
```
eventList =
    [ Event "quantity" 10
    , Event "price"     2
    , Event "price"     3
    , Event "quantity" 30
    ]
```

The the output is
```
new event: quantity
quantity=10

new event: price
price=2

total=20

new event: price
price=3

total=30

new event: quantity
quantity=30

END
```
That is, there is no final `total=90` emitted.

Is this the expected behaviour?

**Comment by agocorona** [comment]
Hi Louis,
I think that this is the intended behaviour in THAT example. To have what you intend, it is a matter of using applicative : 
 
      total=(*) <$> getEvent "qantitity" <*> getEvent "price"

In this case, the total is calculated either a new quantity or price arrives
